services:
  _defaults:
    autoconfigure: true
    public: false
    autowire: true

  Rinsvent\RequestBundle\EventListener\RequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request }

  Rinsvent\RequestBundle\Service\Transformer\:
    resource: '../../../src/Service/Transformer'

